language: c
sudo: required
os:
    - linux
    - windows

dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install -y doxygen python3 python3-yaml libstdc++-4.9-dev
  - wget http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitARMupdate.pl
  - export DEVKITPRO=/opt/devkitpro
  - export DEVKITARM=$DEVKITPRO/devkitARM
  - export PATH=$PATH:$DEVKITARM/bin
  - export ARMIPS=$TRAVIS_BUILD_DIR/deps/armips/armips
  - ./travis/dependencies.sh
  - ./travis/setup.sh
after_success:
  - ./travis/deploy.sh
